sudo: true
language: java
group: edge

addons:
  apt:
    packages:
    - oracle-java9-installer

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
# Get latest install-jdk.sh script
- sh -e /etc/init.d/xvfb start - sleep 10

notifications:
  slack:
    secure: N2waajxdsxS72W4zwrahdtFGH2UZUTboL+RXXy8fmOizD4cm19C8BuSgBWmlxG/EgE1dctrG1sW+jhtPV8t0Jnxi/kdfPLFaB1sqJUJfnP32/0KSgwaH/YpGrphjgY/bZl//pKVpA1THapv0+rBO9+bwcCV0oBmFGDJRZi9dQbJ6qoAGLv1T3EVXzt1Rn+Woh+fl5o8C/Sq5pBHCVWp1ruJxYXAyhSbjcxNTsWvQ9wK1rdBKXrOtyAZjLtFQHCnPfyN3em7zyG6IyQQDUoLxkpuqruKzns9x4U00XuiluQcAIruCgyrO4/4N1wP4wYaE66OLpSnqKVKpOFq8M0kbO+RCdxH5unV6G+G3IYCbaVv0gskcEE00N2eEmZ/YVKND2nPmDfz6yF+WmCXKi8kpZybSxWR6UKd4lwEf27lI1F3SVvMk7xsfVFD487YtJ0v+xCA6Tsv2IjWoCrPtUdzd6Kz7ebomNhefhdhtTVMBJQf7lHHpI6C+2+EMUqGJUBYdD80JJ7vOb4xGFikil3yv7FH9YTstb14FnxaNrZtDrr4kEjCx3P81FkQYVvW+MGF+XtUnhT26rPOE/8qN4CDo1ZnmS2WrICoGRUdz8atlIvLVrfalLTb8Caa/9FLPhjYQunHvdem5PH3VRi7aeSktaKSUlOCeTi7F7D7sxIxBsQ0=
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

matrix:
# **** INCLUDE ****
  include:
# Java 11
  - jdk: openjdk11 
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: openjdk11 
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: openjdk11
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
# Java 10
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.14.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.15.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.14-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.15-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-gradle-2.16-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.14.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.15.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.14-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.15-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    env: BUILDCMD=greetings-maven-2.16-J10.sh
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=greetings-tycho-2.15-J10.sh DISPLAY=:99.0
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=greetings-tycho-2.16-J10.sh DISPLAY=:99.0
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=domainmodel-2.15.sh DISPLAY=:99.0
  - jdk: openjdk10
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      - sh -e /etc/init.d/xvfb start - sleep 10
    env: BUILDCMD=domainmodel-2.16.sh DISPLAY=:99.0
# Java 11 "Oracle JDK"
#  - env: JDK='Oracle JDK 11' BUILDCMD=greetings-gradle-2.14.sh
#    install: . ./install-jdk.sh -F 11 -L BCL
# Java 8
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-gradle-2.12.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-gradle-2.14.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-gradle-2.15.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-maven-2.12.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-maven-2.13.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-maven-2.14.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-maven-2.15.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.12-src.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14-src.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15-src.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=luna-linux
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=mars-linux
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14-src.sh DISPLAY=:99.0 TP=luna-linux
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14-src.sh DISPLAY=:99.0 TP=mars-linux
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14-src.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15-src.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.15-src.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16-src.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=latest
  - jdk: oraclejdk8
    env: BUILDCMD=greetings-tycho-2.16-src.sh DISPLAY=:99.0 TP=latest
  - jdk: oraclejdk8
    env: BUILDCMD=domainmodel-2.15.sh DISPLAY=:99.0
  - jdk: oraclejdk8
    env: BUILDCMD=domainmodel-2.16.sh DISPLAY=:99.0
# Java 9
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.14.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.15.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.16.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.14-J9.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.15-J9.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-gradle-2.16-J9.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-maven-2.14.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-maven-2.15.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-maven-2.16.sh
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.14-J9.sh DISPLAY=:99.0
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=oxygen
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.14.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.15.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=photon
  - jdk: oraclejdk9
    env: BUILDCMD=greetings-tycho-2.16.sh DISPLAY=:99.0 TP=latest
# The following environments are known to fail
  allow_failures:
  - env: JDK='Oracle JDK 11'
script:
- set -e
- sh -e scripts/$BUILDCMD
